USE [tiusr22pl_EstadoUsuarioDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESTADOUSUARIO](
    [ID]          [int] IDENTITY(1,1) NOT NULL,
    [CODIGO]      [varchar](20)  NOT NULL,
    [DESCRIPCION] [varchar](100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USUARIOESTADO](
    [ID]                     [int] IDENTITY(1,1) NOT NULL,
    [USUARIO_IDENTIFICACION] [varchar](50)  NOT NULL,  
    [ESTADOUSUARIO_ID]       [int]          NOT NULL,
    [FECHA_MODIFICACION]     [datetime]     NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USUARIOESTADO]
    ADD DEFAULT (getdate()) FOR [FECHA_MODIFICACION]
GO

ALTER TABLE [dbo].[USUARIOESTADO]
    ADD CONSTRAINT [FK_USUARIOESTADO_ESTADO]
    FOREIGN KEY ([ESTADOUSUARIO_ID]) REFERENCES [dbo].[ESTADOUSUARIO]([ID])
GO

-- Datos iniciales
INSERT INTO [dbo].[ESTADOUSUARIO] ([CODIGO], [DESCRIPCION]) VALUES
('ACTIVO',   'Usuario activo'),
('INACTIVO', 'Usuario inactivo')
GO
