USE [tiusr22pl_FotografiaDB]
GO

CREATE TABLE [dbo].[USUARIOS](
    [USUARIO_IDENTIFICACION] [varchar](255) NOT NULL,
    [NOMBRE]                 [varchar](255) NOT NULL,
    [FOTOGRAFIA_BASE64]      [varchar](max) NULL,
    CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED ([USUARIO_IDENTIFICACION] ASC)
) ON [PRIMARY]
GO


INSERT INTO [dbo].[USUARIOS] ([USUARIO_IDENTIFICACION], [NOMBRE]) VALUES
('101110111', 'Ana Maria Solis Herrera'),
('207890456', 'Carlos Jimenez Mora'),
('304560789', 'Lucia Vargas Rojas'),
('405670123', 'Diego Castro Nunez'),      
('506780234', 'Maria Fernanda Quesada')   
GO

UPDATE [dbo].[USUARIOS] SET [FOTOGRAFIA_BASE64] = '/9j/4AAQSkZJRgABAQEASABIAAD/ejemplo1' WHERE [USUARIO_IDENTIFICACION] = '101110111'
UPDATE [dbo].[USUARIOS] SET [FOTOGRAFIA_BASE64] = '/9j/4AAQSkZJRgABAQEASABIAAD/ejemplo2' WHERE [USUARIO_IDENTIFICACION] = '207890456'
UPDATE [dbo].[USUARIOS] SET [FOTOGRAFIA_BASE64] = '/9j/4AAQSkZJRgABAQEASABIAAD/ejemplo3' WHERE [USUARIO_IDENTIFICACION] = '304560789'
GO
