USE [tiusr22pl_CarnetQRDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARNETQR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO_IDENTIFICACION] [varchar](255) NOT NULL,
	[QR_BASE64] [varchar](max) NOT NULL,
	[FECHA_GENERACION] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARNETQR] ADD DEFAULT (getdate()) FOR [FECHA_GENERACION]
GO


-- Datos de prueba
INSERT INTO [dbo].[CARNETQR] ([USUARIO_IDENTIFICACION], [QR_BASE64], [FECHA_GENERACION]) VALUES
('1-0234-5678', 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', '2026-06-01 08:00:00'),
('2-0456-7890', 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', '2026-06-02 09:15:00'),
('3-0678-9012', 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', '2026-06-03 10:30:00'),
('4-0891-2345', 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', '2026-06-04 11:45:00')
GO

SELECT
    ID,
    USUARIO_IDENTIFICACION,
    LEFT(QR_BASE64, 40) + '...' AS QR_BASE64_PREVIEW,
    FECHA_GENERACION
FROM [dbo].[CARNETQR]
ORDER BY ID
GO
